EBandPlannerROS:
  Ctrl_Rate : 20
  differential_drive: True
  max_acceleration: 0.5
  max_vel_lin: 0.75
  max_vel_th: 1.0
  min_vel_lin: 0.02
  min_vel_th: 0.0
  xy_goal_tolerance: 0.07
  yaw_goal_tolerance: 0.05

